### PR TITLE
fix: invoke initialNavigation when a router is injected

### LINKED ISSUE #280: Bug with location.back()
Hello, I believe I found a bug, where angular testing library doesn't seem to handle `location.back()` scenario.

I have prepared simple project with very basic navigation, specs with TestBed and with Angular Testing Library. In case of TestBed navigation works correctly, but with Angular Testing Library it does not.

https://github.com/meirka/angular-unit-test-navigation

I have similar test in my side project and i'm experiencing the same issue.

Please advise.

Thank you.

### PR DESCRIPTION
**Pull request by timdeschryver**
Fixes #280 

cc @meirka

### CODE REVIEW

File: projects/testing-library/src/lib/testing-library.ts [hunk 1]
```diff
@@ -116,13 +116,12 @@ export async function render<SutType, WrapperType = SutType>(
...
 
-  let router = routes ? inject(Router) : null;
   const zone = inject(NgZone);
-  const navigate = async (elementOrPath: Element | string, basePath = ''): Promise<boolean> => {
-    if (!router) {
-      router = inject(Router);
-    }
 
+  const router = inject(Router);
+  router?.initialNavigation();
```
Comment (meirka) [inline projects/testing-library/src/lib/testing-library.ts:122]: I see, thanks!

**Comment by meirka** [comment]
Which release will be available in?

File: projects/testing-library/src/lib/testing-library.ts (hunk 1 above)
Comment (timdeschryver) [reply projects/testing-library/src/lib/testing-library.ts:122]: It will be available when the PR is merged (now) 😀
