### PR TITLE
fix: add support for InputSignalWithTransform in inputs property

### LINKED ISSUE #483: Regression on components with inputs using a transform function
Hello 👋🏻,

I believe I encountered a regression after bumping the package `@testing-library/angular` from `v17.1.0` to `v17.2.1` while trying to use the new `inputs` property.

The issue arises with components that have inputs using a transform function that changes the type, such as:

```
 title = input.required<TitleObject, string>({
    transform: toTitleObject,
  });
```

Below is the test I wrote : 

```
it('should render', async () => {
    await render(ChildComponent, {
      inputs: {
        title: 'title',
      },
    });
  });
```

In this case, TypeScript raises an error on the render function 🔴:

> Type 'typeof ChildComponent' is not assignable to type 'string'.

When modifying the input so that it has the same type as after the transformation, the TypeScript error is resolved, and the test passes 🟢:

```
it('should render', async () => {
    await render(ChildComponent, {
      inputs: {
        title: {title: 'title'},
      },
    });
  });
```

Please find a reproduction sample below:

https://github.com/mlz11/atl-issue-pr-473

If this is confirmed as a bug, I would love to contribute to resolving it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by mlz11**
Fixes #483 

This PR adds support for `InputSignalWithTransform` in the `inputs` property added by #473.

### CODE REVIEW

File: projects/testing-library/src/lib/models.ts [hunk 1]
```diff
@@ -94,7 +94,11 @@ export type AliasedInputs = Record<string, AliasedInput<unknown>>;
 
 export type ComponentInput<T> =
   | {
-      [P in keyof T]?: T[P] extends Signal<infer U> ? U : T[P];
+      [P in keyof T]?: T[P] extends InputSignalWithTransform<any, infer U>
```
Comment (timdeschryver) [inline projects/testing-library/src/lib/models.ts:97]: I do think it's the case, but can you confirm that InputSignalWithTransform is also exported in Angular 17? (otherwise this is a breaking change)

File: apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts [hunk 2]
```diff
@@ -7,42 +7,45 @@ test('works with signal inputs', async () => {
...
-  expect(computedValue.getByText(/hello world/i)).toBeInTheDocument();
+  expect(computedValue.getByText(/hello world of 4500000000 years old/i)).toBeInTheDocument();
 });
 
 test('can update signal inputs', async () => {
   const { fixture } = await render(SignalInputComponent, {
     inputs: {
       ...aliasedInput('greeting', 'Hello'),
       name: 'world',
+      age: '4500000000',
```
Comment (timdeschryver) [inline apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts:36]: To keep this a bit easier to read 😅

```suggestion
      age: '45',
```

**Review by timdeschryver — COMMENTED** [review]
Thanks @mlz11 , I left a few comments.

File: apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts (hunk 2 above)
Comment (mlz11) [reply apps/example-app/src/app/examples/22-signal-inputs.component.spec.ts]: Modified ✅

File: projects/testing-library/src/lib/models.ts (hunk 1 above)
Comment (mlz11) [reply projects/testing-library/src/lib/models.ts:97]: It seems to be.

I don't know how you would like me to confirm it but this is what I have done : 

1. Created a project under v17 with `npx @angular/cli@17 new angular-test`
2. Added a signal input with transform function and checked that I could explicitly type it 

```
  title: InputSignalWithTransform<number, string> = input.required<
    number,
    string
  >({ transform: numberAttribute });
```
3. Checked imports :
```
import {
  Component,
  input,
  InputSignalWithTransform,
  numberAttribute,
} from '@angular/core';
```

Does that look good to you ?

Comment (timdeschryver) [reply projects/testing-library/src/lib/models.ts:97]: Yea, I verified this as well like this after checking Angular's source code for v17.
Looks good, thanks for the quick PR and updates!

**Comment by timdeschryver** [comment]
@all-contributors please add @mlz11  for code, tests

**Comment by zargham-leanix** [comment]
this PR breaks angular 17 application build

**Comment by zargham-leanix** [comment]
we need to either update version compatibility or make it v17 compatible to angular v17 @timdeschryver @mlz11
